name: Build and publish docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-minify-plugin mkdocs-redirects mkdocstrings-python mkdocs-tech-docs-template mkdocs-awesome-pages-plugin pillow cairosvg
      - run: mkdocs gh-deploy --force
