name: Auto updates

on:
  push:
    branches:
      - "*"

# on:
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --without docs,dev

      # Get the latest release tag for each repo
      - run: export GOVUK_FRONTEND_VERSION=$(make get-latest-release-tag REPO=alphagov/govuk-frontend)
      - run: export GOVUK_FRONTEND_JINJA_VERSION=$(make get-latest-release-tag REPO=LandRegistry/govuk-frontend-jinja)
      - run: export BRANCH_NAME=updates_$(echo $GOVUK_FRONTEND_VERSION | sed 's/\./_/g')_$(echo $GOVUK_FRONTEND_JINJA_VERSION | sed 's/\./_/g')

      # Create a new branch with the BRANCH_NAME
      - name: Create new branch
        run: git checkout -b $BRANCH_NAME

      - name: Upgrade components
        run: make upgrade-components

      # If there were no changes, quit the job
      - name: Check for changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 78
          fi

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Updates for GOV.UK Frontend $GOVUK_FRONTEND_VERSION and GOV.UK Frontend Jinja $GOVUK_FRONTEND_JINJA_VERSION"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create pull request
        run: gh pr create -B main -H $BRANCH_NAME --title 'Update components' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
