name: Auto updates

on:
  push:
    branches:
      - "*"

# on:
#   schedule:
#     - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --without docs,dev

      # Get the latest release tag for each repo
      - run: echo make get-latest-release-tag REPO=alphagov/govuk-frontend >> $GOVUK_FRONTEND_VERSION
      - run: echo make get-latest-release-tag REPO=LandRegistry/govuk-frontend-jinja >> $GOVUK_FRONTEND_JINJA_VERSION
      - run: echo updates__$(echo $GOVUK_FRONTEND_VERSION | sed 's/\./_/g')__$(echo $GOVUK_FRONTEND_JINJA_VERSION | sed 's/\./_/g' >> $GOVUK_FRONTEND_DJANGO_BRANCH_NAME

      - run: env | grep GOVUK

      # Check if the branch already exists
      - name: Check if branch exists
        run: |
          if git rev-parse --verify $GOVUK_FRONTEND_DJANGO_BRANCH_NAME >/dev/null 2>&1; then
            echo "Branch $GOVUK_FRONTEND_DJANGO_BRANCH_NAME already exists"
            exit 78
          fi

      # If there was a PR opened already, exit
      - name: Check if PR exists
        run: |
          if gh pr list --state all --base main --head $GOVUK_FRONTEND_DJANGO_BRANCH_NAME | grep -q $GOVUK_FRONTEND_DJANGO_BRANCH_NAME; then
            echo "PR for $GOVUK_FRONTEND_DJANGO_BRANCH_NAME already exists"
            exit 78
          fi

      # Create a new branch with the GOVUK_FRONTEND_DJANGO_BRANCH_NAME
      - name: Create new branch
        run: git checkout -b $GOVUK_FRONTEND_DJANGO_BRANCH_NAME

      - name: Upgrade components
        run: make upgrade-components

      # If there were no changes, quit the job
      - name: Check for changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 78
          fi

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Updates for GOV.UK Frontend $GOVUK_FRONTEND_VERSION and GOV.UK Frontend Jinja $GOVUK_FRONTEND_JINJA_VERSION"
          git push --set-upstream origin $GOVUK_FRONTEND_DJANGO_BRANCH_NAME

      - name: Create pull request
        run: gh pr create -B main -H $GOVUK_FRONTEND_DJANGO_BRANCH_NAME --title 'Update components' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
